name: 💡 Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: [feature]
type: feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe it clearly below.

  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Describe the feature or improvement you'd like to suggest.
      placeholder: "I would like to have..."
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Why is this useful?
      description: Explain how this feature would help you or others.
      placeholder: "This helps because..."
    validations:
      required: false

  - type: checkboxes
    id: consent
    attributes:
      label: Contributor Agreement
      options:
        - label: I understand that submitting this feature does not guarantee implementation.
          required: true
